export const EXAMPLE_CAMPAIGNS = [
  {
    id: "c1",
    name: "Sneakers Campaign",
    keywords: ["boots", "nike", "adidas", "shoes"],
    offerAmount: 1,
    budget: 100,
    status: true,
    city: "New York",
    radius: 10,
  },
  {
    id: "c2",
    name: "Mobile Phone Campaign",
    keywords: ["phone", "iphone", "samsung", "nokia"],
    offerAmount: 1,
    budget: 1200,
    status: true,
    city: "Los Ageles",
    radius: 20,
  },
  {
    id: "c3",
    name: "Fashion Clothes Campaign",
    keywords: ["fashion", "clothes", "stars"],
    offerAmount: 11234,
    budget: 12300,
    status: false,
    city: "Mediolan",
    radius: 50,
  },
];
